apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubflow
spec:
  ingressClassName: nginx
  rules:
    - host: hubflow.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hubflow-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hubflow-frontend
                port:
                  number: 80
